version: '3'

services:
    apache:
        image: php:7.1-apache
        volumes:
            - .:/var/www/html
        ports:
            - "8000:80"

    poxa:
        image: edgurgel/poxa-automated:v0.7.1
        restart: always
        ports:
            - "8080:8080"
        environment:
            POXA_APP_KEY: application_key
            POXA_SECRET: my_super_secret_key
            POXA_APP_ID: application_id
        volumes:
            - .:/var/www/html
